name: Ubuntu Desktop with VNC + Ngrok

on:
  workflow_dispatch:

jobs:
  ubuntu-desktop:
    runs-on: ubuntu-latest
    timeout-minutes: 9999

    steps:
      - name: Install Desktop Environment & VNC
        run: |
          sudo apt update
          sudo apt install -y xfce4 xfce4-goodies tightvncserver wget unzip
          
          vncserver :1
          vncserver -kill :1

          mkdir -p ~/.vnc
          echo '#!/bin/bash
          xrdb $HOME/.Xresources
          startxfce4 &' > ~/.vnc/xstartup
          chmod +x ~/.vnc/xstartup

          # Set VNC password
          mkdir -p ~/.vnc
          echo -e "vncpass\nvncpass\nn" | vncpasswd

          vncserver :1

      - name: Install Ngrok
        run: |
          wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-linux-amd64.zip
          unzip ngrok-stable-linux-amd64.zip
          chmod +x ngrok

      - name: Start Ngrok Tunnel
        run: |
          ./ngrok authtoken 2wUUz4RS3L7EKQgTtXWtjBBIgO4_4KEspphcDeHTkxmNf8fvM
          ./ngrok tcp 5901 > ngrok.log &
          sleep 10
          echo "🟢 Ngrok Tunnel Started:"
          cat ngrok.log | grep -o 'tcp://[0-9a-zA-Z\.:\-]*'

      - name: Keep Runner Alive
        run: tail -f /dev/null
