name: RustDesk with Ngrok

on:
  workflow_dispatch:

jobs:
  rustdesk-ngrok:
    runs-on: windows-latest
    timeout-minutes: 60

    steps:
      - name: Download RustDesk
        run: |
          Invoke-WebRequest -Uri "https://github.com/rustdesk/rustdesk/releases/latest/download/rustdesk-1.2.3-x64.exe" -OutFile "rustdesk.exe"

      - name: Install RustDesk silently
        run: |
          Start-Process -FilePath ".\rustdesk.exe" -ArgumentList "/silent" -Wait

      - name: Start RustDesk
        run: Start-Process "C:\Program Files\RustDesk\rustdesk.exe"

      - name: Download Ngrok
        run: |
          Invoke-WebRequest -Uri "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-windows-amd64.zip" -OutFile "ngrok.zip"
          Expand-Archive -Path "ngrok.zip" -DestinationPath "."

      - name: Configure Ngrok auth token
        run: .\ngrok.exe authtoken 2wUUz4RS3L7EKQgTtXWtjBBIgO4_4KEspphcDeHTkxmNf8fvM

      - name: Start Ngrok TCP tunnel on port 21112
        run: Start-Process -NoNewWindow -FilePath ".\ngrok.exe" -ArgumentList "tcp 21112" -PassThru

      - name: Wait and show Ngrok TCP endpoint
        run: |
          Start-Sleep -Seconds 10
          Invoke-RestMethod http://127.0.0.1:4040/api/tunnels | Select-Object -ExpandProperty tunnels | Where-Object {$_.proto -eq "tcp"} | Select-Object public_url
